# Site
repository: sohmc/sohmc.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Michael Soh
title: Reliability Practices Evangelist
# email: brett.h@email.co.uk
# website: sohmc.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  sohmc
# stackoverflow_username: "1652942/scuba_mike"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: sohmc
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)
# - title: "Moderna - First Dose"
#   icon: fas fa-syringe

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Broadly skilled in cloud technologies and chaos engineering practices with a background in full-stack web app development, providing innovative solutions to complex challenges.

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Capital One
        link: capitalone.com
        # link_text: boringcompany.com
        sub_title: Manager of Cloud Operations
        caption: November 2018 - Present
        quote: >
          Vulnerability and Cloud Deployment Subject Matter Expert for an entire line of business.
        description: | # this will include new lines to allow paragraphs
            Going from development to production takes a lot of hard work.  I made sure that teams that deployed into the cloud followed all of our policies and guidelines, which limited risk exposure and ensures that teams were well-managed prior to and while deployed in Capital One's AWS environment.
      
      - layout: left
        title: Inova Health Systems
        link: inova.org
        sub_title: Manager of Laboratory Informatics, Analytics, and Applications Support
        caption: August 2014 - November 2018
        description: |
          In Inova's brand new Genomics department, I was responsible for authoring and then enforcing many IT policies regarding data retention and best practices.  I was also directly responsible for moving the team from a Waterfall approach to AGILE, improving our effeciency and throughput.

  - title: Volunteerism # Title for the section
    layout: list # Type of content section (list/text)
    content: $VOLUNTEERISM

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content: $EDUCATION
  
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: php-mysqli
        link: github.com/sohmc/php-mysqli
        # link_text: Project Website
        additional_links:
          - title:  php docker container with mysqli drivers
            icon: fab fa-docker
            url: hub.docker.com/r/sohmc/php-mysqli
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          I created this project to allow me to continue using php's mysqli libraries so I didn't have to refactor my code.  With 10+K pulls, I think it's the most popular thing I've ever created.
    
      - layout: top-middle
        title: cloudflare-ddns-py
        link: github.com/sohmc/cloudflare-ddns-py
        description: | # this will include new lines to allow paragraphs
          This project combines many of my skills: programming, CI/CD pipelines, AWS integration, the works.  It allows home users to maintain their dynamic IP address with a subdomain that they control on Cloudflare.com.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in AWS and software engineering, some of my other interests and hobbies are:
      - Gardening
      - Personal Development
      - Exploring local parks
      - Finding new restaurants


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
