name: Jekyll Site Build
on:
  push:
    branches:
      - 'main'
      - 'converting-to-api-pull'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download resume.json
        run: |
          wget -O resume.json ${{ secrets.RESUME_URL }}
      
      - name: Get Volunteerism
        id: get-volunteerism
        run: |
          echo VOLUNTEERISM_YAML=$(cat resume.json | jq -r '.data.sections.volunteer.items | map(select(.visible == true)) | .[] | "      - title: " + .position + "\n        subtitle: " + .organization + "\n        caption: " + .date + "\n        quote: | #\n          " + .summary')

      - name: PUT Volunteerism
        run: echo $VOLUNTEERISM_YAML
        env: 
          VOLUNTEERISM_YAML: ${{ env.VOLUNTEERISM_YAML }}
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4